version: '3.5'
services:
  discovery:
    image: image:version
    container_name: discovery-service
    ports:
      - "8761:8761"

  config-server:
    image: image:version
    container_name: config-service
    ports:
      - "8081:8081"
    volumes:
      - /home/ubuntu/meru_integration/meru_config:/app/config
    links:
      - discovery

  gateway:
    image: image:version
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  inventory-service:
    image: image:version
    container_name: inventory-service
    ports:
      - "9090:9090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  promotion-service:
    image: image:version
    container_name: promotion-service
    ports:
      - "9299:9299"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  price-service:
    image: image:version
    container_name: price-service
    ports:
      - "9191:9191"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  product-service:
    image: image:version
    container_name: product-service
    ports:
      - "8010:8010"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  product-view-service:
    image: image:version
    container_name: product-view-service
    ports:
      - "8083:8083"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery