FROM alpine/git as clone
WORKDIR /app
RUN git clone https://github.com/prashantrstg/MSA_Team2.git
FROM maven:3.6.3-jdk-11 as build
WORKDIR /app
COPY --from=clone /app/MSA_Team2/Integration /app
WORKDIR "product_service"
RUN mvn install -DskipTests
FROM openjdk:11-jdk
WORKDIR /app
COPY --from=build /app/product_service/target/product_service-0.0.1-SNAPSHOT.jar /app
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","product_service-0.0.1-SNAPSHOT.jar"]
